//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cities_en {
            get {
                object obj = ResourceManager.GetObject("cities_en", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CountrysPhoneNumInfo {
            get {
                object obj = ResourceManager.GetObject("CountrysPhoneNumInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ThreadCount&quot;:100,&quot;DomainInfos&quot;:[{&quot;DomainName&quot;:&quot;Aol&quot;,&quot;DomainListStr&quot;:&quot;aol.com&quot;,&quot;DomainList&quot;:[&quot;aol.com&quot;],&quot;DomainPatternList&quot;:[&quot;(.?aol.com.?)\t(FALSE|TRUE|false|true)\t(.+)\t(FALSE|TRUE|false|true)\t([1-9][0-9]{9,12})\t(.+)\t(.+)&quot;],&quot;CheckingMethod&quot;:&quot;None&quot;},{&quot;DomainName&quot;:&quot;Google&quot;,&quot;DomainListStr&quot;:&quot;google.com&quot;,&quot;DomainList&quot;:[&quot;google.com&quot;],&quot;DomainPatternList&quot;:[&quot;(.?google.com.?)\t(FALSE|TRUE|false|true)\t(.+)\t(FALSE|TRUE|false|true)\t([1-9][0-9]{9,12})\t(.+)\t(.+)&quot;],&quot;CheckingMethod&quot;:&quot;None&quot;},{&quot;DomainName&quot;:&quot;LinkedI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSetting {
            get {
                return ResourceManager.GetString("DefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function generateUUID() {
        ///    var d = new Date().getTime(); // 获取当前时间
        ///    if (typeof performance !== &apos;undefined&apos; &amp;&amp; typeof performance.now === &apos;function&apos;) {
        ///        d += performance.now(); // 使用高精度时间
        ///    }
        ///    return &apos;xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx&apos;.replace(/[xy]/g, function(c) {
        ///        var r = (d + Math.random() * 16) % 16 | 0;
        ///        d = Math.floor(d / 16);
        ///        return (c === &apos;x&apos; ? r : (r &amp; 0x3 | 0x8)).toString(16);
        ///    });
        ///}
        ///
        ///function getTimeStamp() {
        ///    return Math.floor(Date.no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FB {
            get {
                return ResourceManager.GetString("FB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null,[[[2,[&quot;thread-f:1795850316132710027&quot;,[null,null,null,null,null,null,null,[1,[&quot;msg-f:1795850316132710027&quot;],[1712696531482]]]]],[3,[&quot;thread-f:1795850316132710027&quot;,[null,null,null,null,null,null,[[&quot;^k&quot;],[&quot;^ri_hl&quot;,&quot;^i&quot;,&quot;^iim&quot;,&quot;^t_p&quot;,&quot;^t_rd&quot;,&quot;^us&quot;,&quot;^s&quot;,&quot;^a&quot;,&quot;^t_z&quot;,&quot;^afw&quot;],[&quot;msg-f:1795850316132710027&quot;],1712696557272,null,null,null,null,[1712696557271,null,null,12],null,null,[&quot;^sq_ig_i_personal&quot;,[&quot;&quot;],[&quot;^smartlabel_notification&quot;]]]]]]]],[1,2782,null,null,[null,0],null,1],[1712676248858,2,1712696531608,0,25],2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonStr_Postdata_Delete_Gmail {
            get {
                return ResourceManager.GetString("JsonStr_Postdata_Delete_Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [null,null,[null,null,null,null,null,0,null,null,null,1,null,null,1,null,0,1,1,0,1,null,null,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,&quot;pt-PT&quot;,&quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot;,1,0,25,null,0,1,0,1,1,1,1,1,null,1,1,0,1,1,0,0,null,0,1,null,1,0,null,null,0,null,1,0,1,1,null,0,0,0,null,null,1,100,1,1,0,1,0,0,0,1,0,0,1,null,null,0,0],null,&quot;c378541fc6&quot;,null,25,&quot;gmail.pinto-server_20240327.05_p1&quot;,1,5,&quot;&quot;,28800000,&quot;+08:00&quot;,null,null,620257413,&quot;&quot;,&quot;&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonStr_X_Gmail_BTAI {
            get {
                return ResourceManager.GetString("JsonStr_X_Gmail_BTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;deviceId&quot;:&quot;{deviceId}&quot;,&quot;requestId&quot;:0,&quot;requestPayload&quot;:&quot;{\&quot;database\&quot;:1,\&quot;epoch_id\&quot;:0,\&quot;last_applied_cursor\&quot;:null,\&quot;sync_params\&quot;:\&quot;{\\\&quot;full_height\\\&quot;:200,\\\&quot;locale\\\&quot;:\\\&quot;en_US\\\&quot;,\\\&quot;preview_height\\\&quot;:200,\\\&quot;preview_height_large\\\&quot;:400,\\\&quot;preview_width\\\&quot;:150,\\\&quot;preview_width_large\\\&quot;:300,\\\&quot;scale\\\&quot;:1,\\\&quot;snapshot_num_threads_per_page\\\&quot;:15}\&quot;,\&quot;version\&quot;:7945985768756645}&quot;,&quot;requestType&quot;:1}.
        /// </summary>
        internal static string JsonStrDemo_LSPlatformGraphQLLightspeedRequestForIGDQuery {
            get {
                return ResourceManager.GetString("JsonStrDemo_LSPlatformGraphQLLightspeedRequestForIGDQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 导入账号模版_FB {
            get {
                object obj = ResourceManager.GetObject("导入账号模版_FB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 导入账号模版_IG {
            get {
                object obj = ResourceManager.GetObject("导入账号模版_IG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 导入账号模版_IN {
            get {
                object obj = ResourceManager.GetObject("导入账号模版_IN", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
